### ISSUE TITLE
there is no description or readme.md

### ISSUE THREAD

**Issue by 5alidshammout** [bluefeversoft/JSChess#1]
what is this repo, I can't find the readme.md

**Comment by bluefeversoft** [comment]
It's the repo for the tutorial on YouTube. 

https://www.youtube.com/playlist?list=PLZ1QII7yudbe4gz2gh9BCI6VDA-xafLog

There is no readme, which is why you can't find it.

**Comment by 5alidshammout** [comment]
ok thanks

**Comment by 5alidshammout** [comment]
@bluefeversoft can you add the link for the youtube playlist as the website for this repo in the description

**Comment by bluefeversoft** [comment]
> 
> 
> @bluefeversoft can you add the link for the youtube playlist as the website for this repo in the description

Nope. It's linked in the videos.
